### ISSUE TITLE
Keep fabio registered in consul

### ISSUE THREAD

**Issue by robholland** [eBay/fabio#100]
If consul goes away and comes back while fabio is running then fabio's service registration can be lost. If the connection to consul is lost, I think fabio should check if it needs to re-register when re-connected to consul.

**Comment by magiconair** [comment]
yep, it should :)

**Comment by robholland** [comment]
We got bitten by this again today. We use a wildcard DNS entry to point at fabio.service.consul and if consul goes down and comes back, that service entry will stop working even though consul and fabio are both up. I'll see if I can create a PR.

**Comment by robholland** [comment]
Actually we can use the patch in #99 as registrator will automatically maintain a fabio service for us.

**Comment by magiconair** [comment]
I'll have a look later today whether I can fix this properly.

**Comment by magiconair** [comment]
Any idea why your consul servers are going down? We don't really have that issue.

**Comment by magiconair** [comment]
That should fix it.

**Comment by robholland** [comment]
It's because we restart it sometimes to adjust configuration.

**Comment by magiconair** [comment]
Merged it to master. Pls reopen if it causes issues.
