### ISSUE TITLE
Go 1.5 issue

### ISSUE THREAD

**Issue by ptqa** [eBay/fabio#109]
Hi.

I've noticed strange issue when I'm trying to compile fabio with go1.5 compiler. It looks like fabio hangs up and doesn't response to requests for some time and then it outputs everything. I don't get replies even on 404. I try to make requests:
```
root@akuma:~# date; curl -v http://127.1:9999/
Sat Jun 11 21:30:59 UTC 2016
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.1 (127.0.0.1) port 9999 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.1:9999
> Accept: */*
> 
^C
root@akuma:~# date; curl -v http://127.1:9999/
Sat Jun 11 21:31:02 UTC 2016
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.1 (127.0.0.1) port 9999 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.1:9999
> Accept: */*
> 
^C
root@akuma:~# date; curl -v http://127.1:9999/
Sat Jun 11 21:31:04 UTC 2016
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.1 (127.0.0.1) port 9999 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.1:9999
> Accept: */*
> 
^C
```

In logs I see (note time of responses 30 sec later then requests):
```
2016-06-11_21:31:35.93456 2016/06/11 21:31:35 [WARN] No route for 127.1:9999/
2016-06-11_21:31:35.93477 2016/06/11 21:31:35 [WARN] No route for 127.1:9999/
2016-06-11_21:31:35.93486 2016/06/11 21:31:35 [WARN] No route for 127.1:9999/
```

I've tried profiling:
```
(pprof) top
60ms of 60ms total (  100%)
Showing top 10 nodes out of 47 (cum >= 10ms)
      flat  flat%   sum%        cum   cum%
      10ms 16.67% 16.67%       10ms 16.67%  path.Clean
      10ms 16.67% 33.33%       10ms 16.67%  runtime.adjustpointers
      10ms 16.67% 50.00%       10ms 16.67%  runtime.evacuate
      10ms 16.67% 66.67%       10ms 16.67%  runtime.growslice
      10ms 16.67% 83.33%       10ms 16.67%  runtime.usleep
      10ms 16.67%   100%       10ms 16.67%  syscall.Syscall6
         0     0%   100%       10ms 16.67%  encoding/json.(*Decoder).Decode
         0     0%   100%       10ms 16.67%  encoding/json.(*decodeState).object
         0     0%   100%       10ms 16.67%  encoding/json.(*decodeState).unmarshal
         0     0%   100%       10ms 16.67%  encoding/json.(*decodeState).value
```

When I use go 1.6.2 it doesn't happen. Is it expected behaviour?

**Comment by magiconair** [comment]
Try a `kill -QUIT <fabio pid>` and look for the goroutine which hangs in the fabio code. Can you post that here?

**Comment by ptqa** [comment]
@magiconair I'm not sure how to determine which gorouting hangs up, so here is an output
https://gist.github.com/ptqa/dd1ee29d3c67d966a2f5b4de5aa50b04

**Comment by magiconair** [comment]
doesn't look unusual but I'm a bit confused by the hostname you're using in the request: `127.1` doesn't look right. Can you try `curl -v http://127.0.0.1:9999/` ?

**Comment by ptqa** [comment]
It's just a short for 127.0.0.1. But sure:
```
root@akuma:~# curl -v  http://127.0.0.1:9999/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9999 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:9999
> Accept: */*
> 
^C
```

Still hangs up. Logs https://gist.github.com/ptqa/733ddf555506b37b6408a90da24f921e

It's not a really an issue for me, I can use 1.6 compiler, just wanted to let you know.

**Comment by magiconair** [comment]
This isn't in my code. Did you add this?

```
2016-06-11_22:01:28.56105 goroutine 10 [syscall]:
2016-06-11_22:01:28.56105 runtime.CPUProfile(0x0, 0x0, 0x0)
2016-06-11_22:01:28.56105 	/usr/lib/go/src/runtime/cpuprof.go:418 +0x34
2016-06-11_22:01:28.56105 runtime/pprof.profileWriter(0x7fa04a0ea358, 0xc820020118)
2016-06-11_22:01:28.56106 	/usr/lib/go/src/runtime/pprof/pprof.go:599 +0x1c
2016-06-11_22:01:28.56106 created by runtime/pprof.StartCPUProfile
2016-06-11_22:01:28.56106 	/usr/lib/go/src/runtime/pprof/pprof.go:593 +0x145
2016-06-11_22:01:28.56107 
2016-06-11_22:01:28.56107 goroutine 11 [chan receive]:
2016-06-11_22:01:28.56107 github.com/davecheney/profile.Start.func4(0xc82011a870)
2016-06-11_22:01:28.56107 	/home/ptqa/go/src/github.com/davecheney/profile/profile.go:159 +0xef
2016-06-11_22:01:28.56108 created by github.com/davecheney/profile.Start
2016-06-11_22:01:28.56108 	/home/ptqa/go/src/github.com/davecheney/profile/profile.go:165 +0xf44
2016-06-11_22:01:28.56108 
```

Just tried a `GOVENDOREXPERIMENT=1 ~/go1.5.3/bin/go build` and ran `fabio` with the default config on OSX and got this:

```
$ curl -i http://127.0.0.1:9999/
HTTP/1.1 404 Not Found
Date: Sun, 12 Jun 2016 16:22:20 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

OK, thanks for letting me know anyway. I'll keep an eye on this if others have the same issue.

**Comment by magiconair** [comment]
I've noticed that you are working on https://github.com/ptqa/chef-fabio. Would it be OK if I mention this in the README?

**Comment by ptqa** [comment]
Yeah, I've added this for profiling. Sure you can add this to README.

**Comment by aerickson** [comment]
Just experienced hangs with Fabio 1.3.5 and Go 1.5.1. 

Was using https://galaxy.ansible.com/lobsterdore/fabio/ that defaults to 1.5.1. 1.7.4 works fine.

**Comment by ptqa** [comment]
@aerickson current requirement for fabio is go 1.7 or higher

**Comment by magiconair** [comment]
@aerickson Thanks for finding and flagging this in the other project. https://github.com/lobsterdore/ansible-fabio/issues/6. Also, commented on https://github.com/lobsterdore/ansible-fabio/issues/4 which suggests not to build fabio from source in the first place which I think is the better option.
