### ISSUE TITLE
Refactor urlprefix tags

### ISSUE THREAD

**Issue by magiconair** [eBay/fabio#111]
Related open issues: #1, #42, #44, #56, #75, #80, #105, #110, #129, #164 
Related closed issues: #35, #45, #53, #87, #90, #93, #107 

fabio currently uses the `urlprefix-` tag prefix to identify routes. The format is limited to specifying a `host/path` prefix which makes it difficult to allow optional features for a given route. Issue #42 mentions an alternative syntax which provides more options but is still primarily focussed on prefixes. 

[consul issue 1107](https://github.com/hashicorp/consul/issues/1107) mentions a revamp of the API to provide generic KV support for services but doesn't provide a timeline. However, one suggestion is something like [RFC 1464](https://www.ietf.org/rfc/rfc1464.txt) which is used to store arbitrary k/v data in DNS TXT records.

fabio could use this as follows which would provide a generic key/value config mechanism which can also be moved to something else later. Note that RFC 1464 uses the backtick for escaping the `=`, ` ` and the backtick itself.

This would allow a generic mechanism to add options to routes and protocols other than HTTP like TCP to be configured properly. 

```
fabio key=value key=value key=value

e.g.
fabio uri=host/path
fabio uri=host/path proto=http,https
fabio uri=host/path log=true cors=true strip=/path
fabio addr=1.2.3.4:6789 proto=tcp
```

Several design questions come to mind:
- Should multiple prefixes be specified as a multiple `uri` attributes in a single tag or as multiple tags? 

The challenge here would be a length restriction in the tags but we could allow both multiple tags and multiple `uri` attributes to work around this. 
- Should the protocol be specified separately or as part of the URL?

As part of the URL has the benefit of being familiar but will require duplication if a path should be exposed via HTTP  and HTTPS but not WS. Therefore, `uri=host/path proto=http,https` might be more compact.

Another approach would be to use JSON but the quoting makes this more difficult.

**Comment by far-blue** [comment]
Each service in Consul is a single ip/port combination so this is really a 1-2-many mapping problem. This one ip/port could be routed differently (in theory) for http, https, wss and tcp. Clearly not all combinations of these make sense but you get the idea.

So I suggest 1 tag per protocol with each tag starting with the protocol and then providing the protocol-specific details. For http this would be the hostname/path to be routed, for tcp I assume it would just be the listening port, then followed by generic details such as weighting and logging etc.

So you'd have something like:
```
fabio-http foo.com/wibble
fabio-wss foo.com/api strip=/path
fabio-tcp 6789 log=true
```
you could also support mixed protocols such as:
`fabio-http-https foo.com/wibble`

**Comment by far-blue** [comment]
you could use `fabio-proxy` to refer to http & https & wss all at once.

**Comment by magiconair** [comment]
Another approach is to leave the `urlprefix-host/path` unchanged and allow for `urlprefix-host/path key=val key=val ...` This would provide the same flexibility will full backwards compatibility.

**Comment by MilesBehind** [comment]
When do you think, this `key=val key=val` may be implemented? Since spring-cloud-consul supports only this configuration in an application.yml file:
```
spring:
  cloud:
    consul:
      discovery:
        tags: foo=bar, baz=foobar
```
it would be nice if these `key=val key=val` expressions would be supported.

**Comment by magiconair** [comment]
OK, here is what I am going to do:

#### Step 1

Add support for `key=val` options to the existing `urlprefix-` tags. This keeps them backwards compatible and won't break any existing setups. The first option after the tag prefix is the route target. This should also work for a TCP or UDP proxy although it reads a bit awkward.

```
urlprefix-host/path
urlprefix-host/path proto=https strip=/path
urlprefix-1.2.3.4:5555 proto=tcp
```

#### Step 2

Add support for multiple tag prefixes to allow migration from `urlprefix-` to something more generic like `fabio` and add support for a `route=` option as an alias for the route target so that the previous example reads as:

```
fabio route=host/path
fabio route=host/path proto=https strip=/path
fabio route=1.2.3.4:5555 proto=tcp
```

which is equivalent to

```
fabio host/path
fabio host/path proto=https strip=/path
fabio 1.2.3.4:5555 proto=tcp
```

which is equivalent to

```
urlprefix-host/path
urlprefix-host/path proto=https strip=/path
urlprefix-1.2.3.4:5555 proto=tcp
```

Maybe step 2 won't be needed but I'd like to add step 1 ASAP to support additional use cases without breaking existing setups.

**Comment by magiconair** [comment]
Merged new route parser to master

**Comment by magiconair** [comment]
The new route parser is in use. Closing.
