### ISSUE TITLE
fabio should expose a /health endpoint 

### ISSUE THREAD

**Issue by kelseyhightower** [eBay/fabio#112]
I cannot find an easy way to send health checks to fabio from an external loadbalancer such as the Google L3 loadbalancer, which want to make a HTTP request to some endpoint periodically. Does fabio have an easy way to perform health checks against it?

I want to monitor fabio and not it's backends for this specific use case.

**Comment by magiconair** [comment]
Try `127.0.0.1:9998/health` or whatever you have configured for `ui.addr`

**Comment by magiconair** [comment]
That's the health check fabio registers in consul.

**Comment by kelseyhightower** [comment]
Yeah, I found it by looking through the code. Thanks for the fast response.

**Comment by magiconair** [comment]
Cool. Let me know if there's anything else.
