### ISSUE TITLE
Multiple configuration KV

### ISSUE THREAD

**Issue by raben2** [eBay/fabio#113]
is it posible to use multiple consul KVs for more dynamic cluster routing?

**Comment by magiconair** [comment]
Can you explain a bit more what you're after?

**Comment by raben2** [comment]
Behind a dns LoadBalancher i have two fabio and nginx proxies with a shared KV for the global configuration of routes.
This KV contains something like a global routing set for my services. 
If i could set routes in a seperate KV on each proxy i could create something like a blue/green deployment bi switching the route configuration to global.

**Comment by magiconair** [comment]
If you are not using the service discovery feature in consul you can start your fabio instances with different values for `registry.consul.kvpath`. Their manual overrides (i.e. `${registry.consul.kvpath}/config`) would be different. That should do the trick if I understand your question correctly.

**Comment by raben2** [comment]
i see this does the trick. Thanks a lot!

**Comment by magiconair** [comment]
No problem. I am going to close the ticket now. Please re-open if you have more questions.
