### ISSUE TITLE
X-Forwarded-Port should use local port

### ISSUE THREAD

**Issue by robholland** [eBay/fabio#122]
Heya,

The X-Forwarded-Port header should be set to the port on which fabio received the request, not the port that you are going to send the traffic to. The server that's receiving the traffic already knows what port it's on :)

**Comment by robholland** [comment]
This breaks origin checks on applications using rack-protection as it expects the Origin header to include the port number that the backend server is listening on, which is unlikely to ever be correct unless everything happens to be using port 80 internally as well.

**Comment by magiconair** [comment]
@robholland The patch should fix it. Can you test it?

**Comment by robholland** [comment]
Yep, that fixed it for us, cheers!

**Comment by magiconair** [comment]
Merged to master
