### ISSUE TITLE
Path problem

### ISSUE THREAD

**Issue by cabrinoob** [eBay/fabio#124]
Hi,
I have a use case I cannot resolve with fabio:

I have 2 services "Jack" and "John". Jack has two routes /api/dosomething and /api/dootherthing
John has one route /api/hellojohn

John and Jack are deployed through Docker on the same host and registrator registers them into consul. But I have a path problem : John and Jack are using the same prefix (/api). How can I register them into consul.

I tried to tag them with urlprefix-jack/ and urlprefix-john/ but when I call http://fabio-proxy:9999/john/api/hellojohn I have a 404 error.

I need that http://fabio-proxy:9999/**john**/api/* will be redirected to http://docker-host:1234/api/*
and http://fabio-proxy:9999/**jack**/api/* to http://docker-host:5678/api/*

thank you for your help

**Comment by magiconair** [comment]
You have two options:

1. All services register their specific routes, e.g. jack `urlprefix-/api/a`, `urlprefix-/api/b` and for john `urlprefix-/api/c`
2. You register one service with `/api` and the other ones with their specific routes. This makes sense if hack has `urlprefix-/api/a-x` and john has only `urlprefix-/api/z`

**Comment by magiconair** [comment]
Also, path stripping is not implemented right now. See #44 So if the external URL is `http://host.com/john/api` then your service needs to register AND respond to `/john/api`

**Comment by cabrinoob** [comment]
ok, thank you. It's clearer.

**Comment by magiconair** [comment]
Duplicate of #44
