### ISSUE TITLE
Having trouble recognizing routes from consul

### ISSUE THREAD

**Issue by klpauba** [eBay/fabio#137]
I've reviewed the wiki and cannot find a solution to a problem where fabio is not picking up routes from consul (in my particular installation on AWS).

I launch fabio from nomad (as a system task) along with another nomad job (a docker task) that registers with consul using the "registrator" service (another docker instance).  I've arranged for the "urlprefix-/uuid" tag on the service I wish to be handled by fabio.  When I visit the fabio ui, none of the routes (there should be 2) show up.

Here's a shot of the text shown on the consul ui:

<img width="1407" alt="screen shot 2016-07-27 at 11 21 17 am" src="https://cloud.githubusercontent.com/assets/913381/17183248/51d8fcf6-53ec-11e6-947c-1fffdb42be34.png">

If it'll help, here's the specifics of the registration for the service as reported by consul:
`{
  "Node": "klp-coreos-1",
  "Address": "10.139.2.132",
  "ServiceID": "klp-coreos-1:wso2as-1c89fa47-5418-6668-b884-bf00023ed226:9763",
  "ServiceName": "wso2as-http",
  "ServiceTags": [
    "urlprefix-/uuid"
  ],
  "ServiceAddress": "10.139.2.132",
  "ServicePort": 20864,
  "ServiceEnableTagOverride": false,
  "CreateIndex": 4006,
  "ModifyIndex": 4830
}`

Might someone have an idea on why I don't see any routes in the fabio ui?  I've also attempted to use curl to access the endpoint and always get back a 404.

Thanks!

**Comment by klpauba** [comment]
I know, bad form replying to my own issue ...

I'm suspecting that the problem is due to my not having a health check for the service ... I'll add that and see if that's it.

**Comment by magiconair** [comment]
The usual problem for this is the missing health check.

**Comment by klpauba** [comment]
Doh!  Things are working now as expected.  Thanks @magiconair.  Onward in my fabio training ...

**Comment by magiconair** [comment]
:) no worries
