### ISSUE TITLE
Fabio is not adding route, but health check is passing

### ISSUE THREAD

**Issue by artburkart** [eBay/fabio#142]
Here is the information I have:

GitHub issue Fabio

`curl localhost:8500/v1/health/state/any?pretty`

```json
    {
        "Node": "ip-172-31-60-93",
        "CheckID": "helloworld",
        "Name": "HTTP helloworld on port 80",
        "Status": "passing",
        "Notes": "",
        "Output": "HTTP GET http://localhost: 200 OK Output: \u003chtml\u003e\n\u003chead\u003e\n\t\u003ctitle\u003eHello world!\u003c/title\u003e\n\t\u003clink href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'\u003e\n\t\u003cstyle\u003e\n\tbody {\n\t\tbackground-color: white;\n\t\ttext-align: center;\n\t\tpadding: 50px;\n\t\tfont-family: \"Open Sans\",\"Helvetica Neue\",Helvetica,Arial,sans-serif;\n\t}\n\n\t#logo {\n\t\tmargin-bottom: 40px;\n\t}\n\t\u003c/style\u003e\n\u003c/head\u003e\n\u003cbody\u003e\n\t\u003cimg id=\"logo\" src=\"logo.png\" /\u003e\n\t\u003ch1\u003eHello world!\u003c/h1\u003e\n\t\u003ch3\u003eMy hostname is 0c38c2dec137\u003c/h3\u003e\t\u003c/body\u003e\n\u003c/html\u003e\n",
        "ServiceID": "",
        "ServiceName": "",
        "CreateIndex": 0,
        "ModifyIndex": 0
    },
```

Service and healthcheck (`/etc/consul.d/helloworld.json`):

```json
{
    "service": {
        "name": "helloworld",
        "tags": [
            "urlprefix-/hello"
        ],
        "port": 80
    },
    "check": {
        "id": "helloworld",
        "name": "HTTP helloworld on port 80",
        "http": "http://localhost",
        "interval": "10s",
        "timeout": "1s"
    }
}
```

App service

`docker run -d -p80:80 tutum/hello-world`

Extra check:

```
dig @127.0.0.1 -p 8600 helloworld.service.consul
;; ANSWER SECTION:
helloworld.service.consul. 0   	IN     	A      	some.ip.address.here
```

No `route add` event occurs in my fabio logs and it definitely doesn't show up on `localhost:9888/routes`. Am I missing something obvious?

**Comment by magiconair** [comment]
Try setting a service id.

**Comment by magiconair** [comment]
and make sure it is unique per instance. Typical is `helloworld-host:port`

**Comment by artburkart** [comment]
Not sure where I got the idea that the config was correct, but it definitely was not. This was sufficient:

```json
{
    "service": {
        "name": "helloworld",
        "tags": [
            "urlprefix-/hello"
        ],
        "port": 80,
        "check": {
            "http": "http://localhost",
            "interval": "10s",
            "timeout": "1s"
        }
    }
}
```

**Comment by magiconair** [comment]
No worries. You are not the first one with this problem. It is either the missing health check or the missing/non-unique service id. That's why these things are also the first items in the README and Quickstart ;)

**Comment by magiconair** [comment]
Closing for now. Feel free to re-open or to ask more questions.

**Comment by lennart** [comment]
I just stumbled upon this issue since I had a **space** within the consul service `name`. I wasn't expecting fabio to use the service `name` for `route add`. Service ID and check ID were unique (and without spaces).

Maybe this should be noted within the [Quickstart](https://github.com/fabiolb/fabio/wiki/Quickstart)?

**Comment by magiconair** [comment]
@lennart That's a good point. If I would use the service id instead of the name then it would be more difficult to implement weighted routing. I could also update the parser to allow services with names and then quote the name.

**Comment by magiconair** [comment]
@lennart Updated both the Quickstart and the README.

**Comment by magiconair** [comment]
Added #373 to track this.
