### ISSUE TITLE
Specify urlprefix tag with Registrator

### ISSUE THREAD

**Issue by pdoreau** [eBay/fabio#144]
Hello. I'm trying to setup fabio with consul and Registrator on AWS (with ECS/ELB).
[This schema](http://image.slidesharecdn.com/201601dockerfinal-160113214750/95/amazon-ecs-march-2016-12-638.jpg?cb=1456899375) illustrates. In my case, I have several user-facing services (Portal on the schema).

In fabio's documentation, prefix registration is explained through a demo server.
However, how can those urlprefixes be specified through registrator ? /foo => /foo-customable-prefix, /bar => /bar--customable-prefix etc
Is an environment variable usable ?

**Comment by devsprint** [comment]
You can use the environment variable with registration as:
-e SERVICE_TAGS=urlprefix-/burrow

**Comment by pdoreau** [comment]
Thanks I'll try that. How should I handle this in my local computer for development ? Should I specify the tags through Docker compose file ?

**Comment by devsprint** [comment]
you can specify it in docker compose file as:

```
burrow:
  environment:
    - SERVICE_TAGS=urlprefix-/burrow


```

**Comment by pdoreau** [comment]
Alright. It would be usefull to update the documentation with such an example.

About AWS, why does the [demo file](https://github.com/eBay/fabio/blob/master/demo/aws/main.tf) doesn't show any inclusion/execution of Registrator ?

**Comment by magiconair** [comment]
@pdoreau I've added a section about registrator and docker compose to https://github.com/eBay/fabio/wiki/Features#docker-support. Could you and @devsprint have a quick look whether that looks OK?

Re AWS demo file: I've used this only to spin up fabio on AWS to debug a client cert auth problem and for nothing else. Feel free to send a PR if you think this would be useful.

**Comment by devsprint** [comment]
@magiconair looks good to me. I guess that you should mention that using a label instead of env variable also will work with registrator.

**Comment by magiconair** [comment]
@devsprint Could you provide an example for this? I can't seem to find this in their (quite sparse) documentation or I'm just dense.

**Comment by devsprint** [comment]
Let's say that you have the service test/foo that you want to get register by registrator in consul.
First, you have to make sure that you are running the consul agent on the machine, than start the registrator, after you can run the foo/bar service as:

```
$ docker run -d \
    --name=registrator \
    --net=host \        
    --volume=/var/run/docker.sock:/tmp/docker.sock \
    gliderlabs/registrator:latest \
    consul://localhost:8500

$ docker run -d -p 80:8080 \
  -e SERVICE_8000_CHECK_HTTP=/foo/healthcheck  \
  -e SERVICE_8000_NAME=foo \
  -e SERVICE_CHECK_INTERVAL=10s \
  -e SERVICE_CHECK_TIMEOUT=5s  \
 -e SERVICE_TAGS=urlprefix-/foo \
  test/foo

```

**Comment by magiconair** [comment]
Thx. I've updated the https://github.com/eBay/fabio/wiki/Features#registrator example accordingly.

**Comment by devsprint** [comment]
@magiconair LGTM excepting the port binding. I have edited my reply just to avoid confusion.

**Comment by magiconair** [comment]
Fixed

**Comment by magiconair** [comment]
ok, closing this one now. Feel free to comment or to re-open.

**Comment by pdoreau** [comment]
Alright thanks but is port 80 param useful ?
`docker run -d -p 80:8000`
As consul provide us the host port number when needed, It would be better to let docker choose it
`docker run -d -p 8000`

**Comment by devsprint** [comment]
@pdoreau sure but this is a decision that the developer may take. there will be services where you must bind to a specific host port.
