### ISSUE TITLE
Can use fabio to deal HTTP2.0 request

### ISSUE THREAD

**Issue by gavenwangcn** [eBay/fabio#148]
can use Fabio to deal HTTP2.0 traffic , that means Fabio can support HTTP2.0 Agreement ?

**Comment by magiconair** [comment]
Fabio acts as an HTTP/2 server but will not make HTTP/2 requests to the backend servers. Since the backend servers are usually physically close to fabio this isn't too much of a problem. 

```
Internet - HTTP/1.1 or HTTP/2 -> fabio - HTTP/1.1 -> server
```

Does that answer your question?

**Comment by magiconair** [comment]
I'll close this for now. Feel free to comment or re-open.
