### ISSUE TITLE
fabio g-rpc

### ISSUE THREAD

**Issue by rgardam** [eBay/fabio#156]
Hi,
I just started looking at fabio and it looks like a really nice project. I would also like to couple this with g-rpc, but grpc only seems to support HTTP2 between server and client. 

Is there any plan to talk HTTP2 between fabio and client?

Thanks.

**Comment by magiconair** [comment]
Not yet, but that can change.

**Comment by rgardam** [comment]
Ok thanks for the feedback! :)
