### ISSUE TITLE
OT: logo for the eBay organization

### ISSUE THREAD

**Issue by dandv** [eBay/fabio#158]
Would be nice to have the eBay logo at https://github.com/eBay

Thanks!

**Comment by magiconair** [comment]
@vhuang01 I think that's something for you.

**Comment by vhuang01** [comment]
Agreed, I’ll try to find a brand approved logo.  Thanks!

**Comment by vhuang01** [comment]
Done, closing this issue.  Thanks for bringing this to my attention!
