### ISSUE TITLE
Support glob host matching

### ISSUE THREAD

**Issue by discobean** [eBay/fabio#163]
Apologies if there is a feature for this already, I wasn't able to find it.

I was curious if consul can support wildcard domains in the urlprefix.

```
E.g. *.mydomain.com/route
Or .mydomain.com/route
Or .*\.mydomain.com\/route
```

Or something similar to that effect?

**Comment by magiconair** [comment]
Isn't the `glob` matcher doing this already? Checking

**Comment by magiconair** [comment]
Ah, no. This only checks globs against the path. Might make sense to extend this to the full URL. Want to work on a PR?

**Comment by magiconair** [comment]
#45 has a lengthy discussion about the topic. Might be useful to dive into this first. Can I leave the investigation for this one with you for the moment? I'm a bit time constrained. Otherwise, it will have to wait a bit.

**Comment by discobean** [comment]
No problem I will investigate, thanks so much
