### ISSUE TITLE
Consul cert store URL with token not parsed correctly

### ISSUE THREAD

**Issue by magiconair** [eBay/fabio#172]
When a URL for a consul certificate store contains a token then this token is not stripped off properly. Therefore, this URL does not work:

```
http://localhost:8500/v1/kv/path/to/cert?token=123
```

**Comment by cpredmann** [comment]
In testing, it looks like this now works; thanks for the fix

**Comment by magiconair** [comment]
@cpredmann awesome. Thanks for testing. Closing.
