### ISSUE TITLE
Add HTTPS upstream support

### ISSUE THREAD

**Issue by ak66982** [eBay/fabio#181]
Hi,

Is there any way to register https:// backends without using tcp+sni, with fabio performing ssl termination on the client side, and talking https to the backends (re-encoding traffic) ?  The reason for this is that frontend certificate is not the same as the ones that are used internally, so plain tcp+sni will not work.

Regards,
Alex

**Comment by magiconair** [comment]
fabio does not support that yet. I'll probably add that at a later stage when I'm addressing #111

**Comment by Narrowbeam** [comment]
Would be really good to see this - its the only feature stopping our adoption of this project.  Fingers crossed you can add it fairly soon.

**Comment by magiconair** [comment]
@Narrowbeam It is on the list. I've spent some time refactoring the listener and proxy code in the `release-branch-1.4` to make this simpler. The addition of the TCP proxy was already a step in that direction. So stay tuned. :)

**Comment by shadowfax-chc** [comment]
@magiconair is this as simple as adding a new conditional in [registery/consul/service.go](https://github.com/eBay/fabio/blob/master/registry/consul/service.go#L116-L119)?

Not sure what kind of configuration you might want around it.

**Comment by magiconair** [comment]
It could be. However, I think that you need to have some cert management options as well since upstream certs are probably self-signed. There may be more but I think that would be a good start. 

Frank Schröder

**Comment by magiconair** [comment]
Thanks @shadowfax-chc for implementing this. This is great progress. I'll release 1.4.2 soon with this.
