### ISSUE TITLE
Vault CA Certificate

### ISSUE THREAD

**Issue by calvinmorrow** [eBay/fabio#182]
Is there any way to specify a supplemental certificate authority file for connections to Vault?  Our Vault is configured with a self-signed certificate and Fabio is throwing `x509: certificate signed by unknown authority` on connections to it.

The Vault api vendor code looks like it uses the env var VAULT_CACERT but as far as I can tell only the VAULT_TOKEN and VAULT_ADDR are used by Fabio.

Other than adding that certificate to the list of Go's trusted root certs ... any way to get that connection to succeed?  We're using the Docker image so I'd rather avoid monkey patching the trusted cert file if possible.

**Comment by magiconair** [comment]
Traveling now. I'll have a look later

**Comment by magiconair** [comment]
@calvinmorrow I think I'm not initializing the Vault client properly. I've pushed a change that might do what you need. Would be great if you could test it since I'm shooting from the hip.

**Comment by calvinmorrow** [comment]
@magiconair Thanks.  I can confirm your commit solves the issue.  Fabio is now pulling certificates from Vault.

**Comment by magiconair** [comment]
Cool. I'll merge it.

**Comment by magiconair** [comment]
Merged to master.
