### ISSUE TITLE
WebSockets not working with IE10 - header casing.

### ISSUE THREAD

**Issue by ReimerA** [eBay/fabio#183]
After some research into a problem with websockets through fabio when using IE10, I have discovered that IE10 sends the following header:

Upgrade: Websocket

It seems fabio i not treating this header value wrong because of the casing.

I have a SignalR application behind fabio, and I get an error (400), and SignalR falls back on longpolling. However if I edit the request for initiating the websocket connection in fiddler, and change the header to the below it seems to work (the request gets a 101 back not a 400) (notice the casing).

Upgrade: websocket

**Comment by magiconair** [comment]
Merged the fix to master. You'll have to build a version yourself for now. I'll release a fix version in a couple of days. I'll close this one now. Feel free to re-open or comment if this does not solve your issue.
