### ISSUE TITLE
Is this the expecting behavior of Fabio with paths?

### ISSUE THREAD

**Issue by fjromerom** [eBay/fabio#187]
I have 2 apps runnin in Nomad with next prefix:

First service: -urlprefix-/test
Second service: -urlprefix-/test2

When I request to Fabio at the next URL:

example.com/test2foo --> second service

I get the response from service with tag "urlprefix-/test2". But I expected to get a 404 not found because the path is different.

**Comment by leprechau** [comment]
The route should be explicit.  When doing bath based routing even in HAProxy we always make sure our ACLs are ```/route/``` ... terminated with a trailing slash.  This ensures that the behavior you posted doesn't happen.

**Comment by fjromerom** [comment]
Thanks!
