### ISSUE TITLE
missing 'cs' in map

### ISSUE THREAD

**Issue by raben2** [eBay/fabio#189]
Hi, 

i finally got to update my fabio installation to 1.3.4 and now i am trying to use the path based certificate store.

I need to setup a secondary cs for client cert usage because i only use it with several integration systems.

```
proxy.cs = cs=main;type=path;cert=/etc/nginx/certs;refresh=3s, \
                 cs=client;type=path;cert=/etc/nginx/cs1;clientca=/etc/nginx/cs1/client;refresh=3s
```

When i now start up fabio i get the following error:

`[FATAL] 1.3.4. missing 'cs' in map[ cs:client type:path cert:/etc/nginx/cs1 clientca:/etc/nginx/comonea/cs1 refresh:3s]
`
BTW. Your Wiki has an error within the examples

```
 # path based certificate source
 proxy.cs = cs=some-name;type=path;path=path/to/certs
```
should be:
`proxy.cs = cs=some-name;type=path;cert=path/to/certs`

Thanks in advance
Georg

**Comment by magiconair** [comment]
Looking

**Comment by magiconair** [comment]
Fixed wiki.

**Comment by magiconair** [comment]
The parser for the `key=val;key=val` lists did not trim spaces from the `key`s. Removing the space in the argument works around the issue. This patch fixes that.

**Comment by raben2** [comment]
thank you, it purrs like a kitten now
