### ISSUE TITLE
(Docker) Error initializing backend.

### ISSUE THREAD

**Issue by strarsis** [eBay/fabio#19]
When starting fabio as docker container using the following command 
````
docker run -d -p 9999:9999 -p 9998:9998 -v $PWD/fabio/fabio.properties:/etc/fabio/fabio.properties magiconair/fabio:1.0.6
````
the container will exit and I get this error in docker logs:
````
2015/12/06 21:42:01 [INFO] Version 1.0.6 starting
2015/12/06 21:42:01 [FATAL] Error initializing backend. Get http://localhost:8500/v1/agent/self: dial tcp [::1]:8500: getsockopt: connection refused
````

Thank you and
with best regards

**Comment by magiconair** [comment]
Did you override `consul.addr` to point to a consul agent? By default fabio assumes that there is a consul agent running on the same machine which most likely isn't the case for the docker container.

**Comment by strarsis** [comment]
Can I pass those settings, partly (overriding), as command line argument?
Because I would use it together with docker-compose or maestrodev-ng (or swarm?) 
and then it would be helpful to pass the ip address of the consul server container.

Thank you and
with best regards

**Comment by magiconair** [comment]
Yes, smart idea. Thx
