### ISSUE TITLE
Q: Fabio Setup Error

### ISSUE THREAD

**Issue by vjappidi** [eBay/fabio#200]
We have consul agent running on 3 windows servers as cluster with services.
When i run fabio on different server with command line  fabio -registry.consul.addr ipaddress 

I am getting the below error
  [FATAL] Error initializing backend. Get http://ipaddr/v1/agent/self: dial tcp ipaddr:80: connectex: No   connection could be made because the target machine actively refused it.

Please help me in resolving the issue

Thanks,
Vijay

**Comment by magiconair** [comment]
Try adding the port, e.g. 1.2.34:8500

Frank Schröder

**Comment by vjappidi** [comment]
I tried  adding port ipaddr:8500,but getting the same error

Thanks,
Vijay

**Comment by magiconair** [comment]
Can you share how you are running fabio (cmd line args, env vars) and the startup log including the runtime config?

**Comment by vjappidi** [comment]
Please find below the log

C:\fabio>fabio-1.3.4-go1.7.3-windows_amd64 -registry.consul.addr 192.168.196.XXX:8500
2016/12/01 08:56:43 [INFO] Runtime config
{
    "Proxy": {
        "Strategy": "rnd",
        "Matcher": "prefix",
        "NoRouteStatus": 404,
        "MaxConn": 10000,
        "ShutdownWait": 0,
        "DialTimeout": 30000000000,
        "ResponseHeaderTimeout": 0,
        "KeepAliveTimeout": 0,
        "ReadTimeout": 0,
        "WriteTimeout": 0,
        "FlushInterval": 1000000000,
        "LocalIP": "192.168.196.XXX",
        "ClientIPHeader": "",
        "TLSHeader": "",
        "TLSHeaderValue": "",
        "GZIPContentTypesValue": "",
        "GZIPContentTypes": null
    },
    "Registry": {
        "Backend": "consul",
        "Static": {
            "Routes": ""
        },
        "File": {
            "Path": ""
        },
        "Consul": {
            "Addr": "192.168.196.XXX:8500",
            "Scheme": "http",
            "Token": "",
            "KVPath": "/fabio/config",
            "TagPrefix": "urlprefix-",
            "Register": true,
            "ServiceAddr": ":9998",
            "ServiceName": "fabio",
            "ServiceTags": null,
            "ServiceStatus": [
                "passing"
            ],
            "CheckInterval": 1000000000,
            "CheckTimeout": 3000000000
        }
    },
    "Listen": [
        {
            "Addr": ":9999",
            "Proto": "http",
            "ReadTimeout": 0,
            "WriteTimeout": 0,
            "CertSource": {
                "Name": "",
                "Type": "",
                "CertPath": "",
                "KeyPath": "",
                "ClientCAPath": "",
                "CAUpgradeCN": "",
                "Refresh": 0,
                "Header": null
            },
            "StrictMatch": false
        }
    ],
    "CertSources": {},
    "Metrics": {
        "Target": "",
        "Prefix": "{{clean .Hostname}}.{{clean .Exec}}",
        "Names": "{{clean .Service}}.{{clean .Host}}.{{clean .Path}}.{{clean .TargetURL.Host}}",
        "Interval": 30000000000,
        "GraphiteAddr": "",
        "StatsDAddr": "",
        "CirconusAPIKey": "",
        "CirconusAPIApp": "fabio",
        "CirconusAPIURL": "",
        "CirconusCheckID": "",
        "CirconusBrokerID": ""
    },
    "UI": {
        "Addr": ":9998",
        "Color": "light-green",
        "Title": ""
    },
    "Runtime": {
        "GOGC": 800,
        "GOMAXPROCS": 4
    },
    "ListenerValue": [
        ":9999"
    ],
    "CertSourcesValue": null
}
2016/12/01 08:56:43 [INFO] Version 1.3.4 starting
2016/12/01 08:56:43 [INFO] Go runtime is go1.7.3
2016/12/01 08:56:43 [INFO] Using routing strategy "rnd"
2016/12/01 08:56:43 [INFO] Using routing matching "prefix"
2016/12/01 08:56:43 [INFO] Setting GOGC=800
2016/12/01 08:56:43 [INFO] Setting GOMAXPROCS=4
2016/12/01 08:56:43 [INFO] Metrics disabled
2016/12/01 08:56:44 [FATAL] Error initializing backend. Get http://192.168.196.XXX:8500/v1/agent/self: dial tcp 192.168.196.XXX:8500: connectex: No connection could be made because the target machine
actively refused it.

Thanks,
Vijay

**Comment by vjappidi** [comment]
Could you please help on the above issue.

Thanks,
Vijay

**Comment by magiconair** [comment]
This is a networking problem. Does 'telnet 192.168.196.XXX:8500' work?

Frank Schröder

**Comment by magiconair** [comment]
@vjappidi I am going to close this issue for now. If you find that this isn't a networking related issue on your end or if you have other related issues please feel free to comment and I can re-open the issue, if necessary.
