### ISSUE TITLE
Support deleting routes by tag

### ISSUE THREAD

**Issue by killcity** [eBay/fabio#201]
Is there a way to setup an override that will send 0% traffic to nodes that have a specific tag. That way we can still see the node is a member of the pool but temporarily not having any traffic sent to it because of it's tag status.

Examples:

Route set to 0% based on tag "maint_mode" (using -1 as an example of sending 0% traffic)
```route weight appservice testsite.com/app weight -1 tags "maint_mode"```

Route deleted based on tag "maint_mode"
```route del appservice testsite.com/app tags "maint_mode"```

Cheers

**Comment by magiconair** [comment]
Like `route del svc tags "tag"`? We were just talking about this. Not hard to add but not there yet. 

Frank Schröder

**Comment by killcity** [comment]
Yah, precisely. Looks like you read my comment before I edited with examples. You're too quick. :)

**Comment by magiconair** [comment]
I'll add that after I've fixed the weighing bug. (#186)

**Comment by killcity** [comment]
Thanks again. Need to learn Go for 2017 so I can contribute :)

**Comment by magiconair** [comment]
Implementing this pushed me into refactoring the table parser tests a bit more. This patch adds support for 

```
# delete routes of <svc> which have tags 'a' and 'b'
route del svc tags "a,b"

# delete routes which have tags 'a' and 'b'
route del tags "a,b"
```

**Comment by magiconair** [comment]
Merged the change to master. Please test.
