### ISSUE TITLE
Q: security code review

### ISSUE THREAD

**Issue by chiel1980** [eBay/fabio#204]
Hi,

Did you guys ever did a security review on your code by an external party?
And if yes, are you willing to share these results or can we find it back in some specifc commits?
We are scheduling a code review by an external security company and if you want, we would like to share these results with you/the community as feedback to improve the product (if anything has been found) :)

Michiel

**Comment by magiconair** [comment]
@chiel1980 No, we didn't and yes, I'm interested. If you've found something then I'd prefer if you first disclose to me so that I can prepare a fix first and disclose publicly later. 

Frank

**Comment by magiconair** [comment]
@chiel1980 Any news on this? Just curious.

**Comment by chiel1980** [comment]
Hi, because of the costs of the code review of the components we wanted to review and since you/eBay is running it in production, we decided to not do the code review and focus on higher risk components.
A cost/risk tradeoff so to speak.

**Comment by magiconair** [comment]
Fair enough :) Closing this one then.
