### ISSUE TITLE
How to do the load balancing of fabio itself?

### ISSUE THREAD

**Issue by tonysongtl** [eBay/fabio#208]
Is it possible to support multiple instances of fabio?  how the route will be?

**Comment by magiconair** [comment]
Please have a look at https://github.com/ebay/fabio/wiki/Deployment and let me know whether that answers your question.

**Comment by magiconair** [comment]
@tonysongtl I'm going to close this one for now. Feel free to comment and I'll re-open if necessary or create another issue.
