### ISSUE TITLE
Consul registration won't disable

### ISSUE THREAD

**Issue by momania** [eBay/fabio#209]
When running Fabio as a Nomad job, the Consul registration uses the ip address of the Docker bridge. So I'd like to disable this registration so I can register it in the Nomad job, but passing the command line param that should switch this has no effect.

```
task "fabio" {
      driver = "docker"

      config {
         image = "magiconair/fabio"
         command = "/fabio"
         args = [
           "-registry.consul.addr", "169.254.0.1:8500",
           "-registry.consul.register.enabled", "false"
         ]
     }
}
```

The different Consul address is picked up correctly, but not the registration flag.

```
"Registry": {
        "Backend": "consul",
        "Static": {
            "Routes": ""
        },
        "File": {
            "Path": ""
        },
        "Consul": {
            "Addr": "169.254.0.1:8500",
            "Scheme": "http",
            "Token": "",
            "KVPath": "/fabio/config",
            "TagPrefix": "urlprefix-",
            "Register": true,
            "ServiceAddr": ":9998",
            "ServiceName": "fabio",
            "ServiceTags": null,
            "ServiceStatus": [
                "passing"
            ],
            "CheckInterval": 1000000000,
            "CheckTimeout": 3000000000
        }
    },
```

Any idea what might be going wrong here?

**Comment by magiconair** [comment]
Try `"-registry.consul.register.enabled=false"`. Boolean flags should be passed with an `=false` AFAIR. That works for me here.

**Comment by momania** [comment]
Shit, was just about to reply since I just figured that out myself too. 😆 

Thanks for the reply anyway, and sorry for the noise!

**Comment by magiconair** [comment]
No worries. Glad you found it. :) Let me know if there is something else.

**Comment by xbx** [comment]
Maybe:
https://github.com/eBay/fabio/blob/128b59ccb543832312ea2050b8154b4fd0ee93b8/registry/consul/backend.go#L40

Should it be cfg.Registry.Consul.Register?

https://github.com/eBay/fabio/blob/2117ae94ef239b30b95034df0b5c2b776f9df465/config/load.go#L152

**Comment by magiconair** [comment]
@xbx No since in this context `cfg` is `*config.Consul`.
