### ISSUE TITLE
Q: Where to add root cert for signed client certs

### ISSUE THREAD

**Issue by raben2** [eBay/fabio#225]
Hi Frank,

i have a question about the usage of a self signed ca in combination with clientca certs
I created a certificate authority with root and intermediate certs which i imported in my Fabio Servers Trust store.
On CentOS7 with update-ca-certificates

When i now use the intermediate certificate to issue a client certificate it can not be verified by fabio. 

`
 tls: failed to verify client's certificate: x509: certificate signed by unknown authority
`

the proxy configuration is:
```
cs=db;type=path;cert=/etc/nginx/certs;clientca=/etc/nginx/clientcrts;refresh=3s
proxy.addr = 0.0.0.0:8443;cs=db;proto=https;caupgcn=intca.domain.de
```

did i miss something? where do i have to trust the for fabio?

**Comment by magiconair** [comment]
Good question.

Just to clarify: `/etc/nginx/clientcrts` contains client certs which were signed by a self-signed root cert? Now you're wondering where the root cert should be so that fabio accepts them?

**Comment by raben2** [comment]
yes right.

**Comment by magiconair** [comment]
OK, I'll try to reproduce this and get back to you.

`caupgcn` does something different AFAIR. It "upgrades" a self-signed certificate to be used for client cert authentication (`IsCA` flag set) if the CN matches the provided name. This allows you to use a self-signed cert generated by the AWS console as a client cert. Otherwise, Go wouldn't accept it since the `CA` flag isn't set.

**Comment by raben2** [comment]
Ah ok i see.
The problem is the same if i leave out the caupgcn flag. 
imagine i want to accept all client certs from my self signed ca. What can i do?

**Comment by magiconair** [comment]
Not sure yet. Looking now.

**Comment by magiconair** [comment]
Try adding the ca cert block to the client ca directory. That should pick it up. At least it does for me here. I'll push a small change that generates test certs with openssl and I should also update the startup log messages of the cert stores a bit.

**Comment by raben2** [comment]
As always it works like a charm. Thank you!

**Comment by magiconair** [comment]
Glad to help. :)
