### ISSUE TITLE
Load balancing between multiple service cluster nodes

### ISSUE THREAD

**Issue by TargetFocussed** [eBay/fabio#231]
I wonder if can load balance for multiple services? If so how can I do this ?

Example :

service 1="hello-world"
service 2="Python-service"

Lets say Hello-world is running on 3 containers and Python-service is running on 3 containers

Hello world containers
Container 1 : 192.168.1.1(Hello server + Registratore, consul agent)
Container 2 : 192.168.1.2(Hello server + Registratore, consul agent)
Container 3 : 192.168.1.3(Hello server + Registratore, consul agent)

Python containers 
Container 4 : 192.168.2.1 (Python server + Registratore, consul agent)
Container 5 : 192.168.2.2(Python server + Registratore, consul agent)
Container 6 : 192.168.2.3(Python server + Registratore, consul agent)

and say ....consul service is running on a different container ..192.168.3.1

Now ...when asked for "helloworld service , it should round robin between the 3 helloworld containers, where as when asked for "python-service" .... it should round robin between the 3 phython containers.

My assumption is as follows 
                                         + -----> Service A cluser nodes 
                                          | 
Consul Server + Fabio ----+
                                          |
                                          +----> Service B Clusetr nodes

Is so how do I configure this ?.

thanks

**Comment by magiconair** [comment]
Fabio does that automatically. There is no special configuration needed. Once you register your services in consul with the correct `urlprefix-` tags fabio will update a routing table every time you start, stop, install or remove a service. 

https://github.com/eBay/fabio#getting-started

**Comment by magiconair** [comment]
Going to close this since you seem to create new issues for different questions - which is fine.
