### ISSUE TITLE
Not able to connect to fabio UI ... I wonder if I miss any specifics ?.

### ISSUE THREAD

**Issue by TargetFocussed** [eBay/fabio#234]
Not able to connect to fabio UI ... I wonder if I miss any specifics ?.

Here is how I started the fabio

Without UI address
$sudo docker run -d -p 9999:9999 -p 9998:9998 --name=fabio -e 'registry_consul_addr=10.193.6.129:8500' magiconair/fabio

With UI address , I see a FATAL error 
 sudo docker run -d -p 9999:9999 -p 9998:9998 --name=fabio -e 'ui_dir=10.193.6.129' -e 'registry_consul_addr=10.193.6.129:8500' magiconair/fabio

ubuntu1@ubuntu1:~$ sudo docker ps -a
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                   NAMES
6db6fe5d0f01        magiconair/fabio     "/fabio -cfg /etc/fab"   About an hour ago   Up About an hour    9998/tcp, 10.193.6.129:9999->9999/tcp   fabio
38951919b70d        uifd/ui-for-docker   "/ui-for-docker"         About an hour ago   Up About an hour    10.193.6.129:9000->9000/tcp             angry_kirch
9885b31fecd1        wdijkerman/consul    "/sbin/tini -- /bin/s"   5 days ago          Up 5 days                                                   consul-server
ubuntu1@ubuntu1:~$ curl http://localhost:9998/routes
curl: (7) Failed to connect to localhost port 9998: Connection refused
ubuntu1@ubuntu1:~$ curl http://127.0.0.1:9998/routes
curl: (7) Failed to connect to 127.0.0.1 port 9998: Connection refused
ubuntu1@ubuntu1:~$ curl http://10.193.6.129:9998/routes
curl: (7) Failed to connect to 10.193.6.129 port 9998: Connection refused
ubuntu1@ubuntu1:~$

**Comment by magiconair** [comment]
Again, I'm no Docker expert and I suggest you look at the Docker compose setup referenced by @raben2 in #223. However, the following steps work for me:

```
# start consul in a container and note the IP address it is using
# in my case 172.17.0.2
docker run -e 'CONSUL_BIND_INTERFACE=eth0' consul

# start fabio and expose the ports
docker run -p 9999:9999 -p 9998:9998 -e 'registry_consul_addr=172.17.0.2:8500' magiconair/fabio

# query proxy interface
$ curl -i localhost:9999/
HTTP/1.1 404 Not Found
Date: Tue, 07 Feb 2017 13:06:34 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

# query ui interface
$ curl -i localhost:9998/
HTTP/1.1 303 See Other
Location: /routes
Date: Tue, 07 Feb 2017 13:06:19 GMT
Content-Length: 34
Content-Type: text/html; charset=utf-8

<a href="/routes">See Other</a>.
```

**Comment by magiconair** [comment]
Going to close this since you seem to create new issues for different questions - which is fine.
