### ISSUE TITLE
How does services get in to router table of fabio

### ISSUE THREAD

**Issue by TargetFocussed** [eBay/fabio#237]
I have a single host machine

1. Docker 1 => Consul-Server
2. Docker 2 ==> Registrator
3. Docker 3 ==> Fabio
4. Docker 4 ==> Hello world

I am not able to see Hello World in the routing table ?.

Here are the commands I tried....did I miss any specifics ?

```
sudo docker run -d  -h consul-server1 --name consul-server1 -p 8300:8300 -p 8301:8301 -p 8301:8301/udp -p 8302:8302 -p 8302:8302/udp -p 8400:8400 -p 8500:8500 -p 8600:53/udp wdijkerman/consul -server -bootstrap -ui -ui-dir /consul/ui -advertise 10.193.6.129

sudo docker run -d -h consul-client1 --name consul-client1 -p 8300:8300 -p 8301:8301 -p 8301:8301/udp -p 8302:8302 -p 8302:8302/udp -p 8400:8400 -p 8500:8500 -p 8600:53/udp wdijkerman/consul -join 10.193.6.129 -advertise 10.193.16.117

sudo docker run -d -h registrator --name registrator -v /var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator consul://10.193.6.129:8500

sudo docker run -d -h fabio --name fabio -p 10.193.6.129:9999:9999 -p 10.193.6.129:9998:9998 -e 'registry_consul_addr=10.193.6.129:8500' magiconair/fabio

sudo docker run -d -h hello-world-1 --name hello-world-1 -p 10.193.6.129:80:8000  -e SERVICE_TAGS=urlprefix-/ -e SERVICE_NAME=hello-world tutum/hello-world
```

**Comment by magiconair** [comment]
What does `curl http://10.193.6.129:8500/v1/health/hello-world` say?

**Comment by TargetFocussed** [comment]
empty ... no values / output

**Comment by magiconair** [comment]
I'm sorry but I'm out of advice. My gut feel is that you are doing something fundamentally wrong and that this is most likely a simple issue. I do not believe that you have found a bug in either fabio or consul. However, you have chosen a complex setup with spring-boot, registration frameworks, and docker to start with.

What I would suggest at this point is to throw your sample project away. Don't use Docker or a framework at this point. Start with a simple java program that has just a Main class and uses only the consul api library. Make sure you read the https://github.com/eBay/fabio#getting-started section and make sure your service follows that. If you need inspiration you can look at the `main` function in `demo/server/server.go`. It has only 120 lines and does everything you need to do. (https://github.com/eBay/fabio/blob/master/demo/server/server.go#L46-L166)

Run consul, fabio and your app instances locally in separate terminal windows, binding to 127.0.0.1 (again do not use Docker at this point) and figure out how to make that work. Then start a second instance of your service and make that work. If it doesn't then read the fabio Getting Started again and figure out how to get data out of consul using the command line tools. Then one step at a time add a different component towards the setup you want to have. What you will learn with this approach is how to check whether something works and where and how to look if it doesn't. 

Please feel free to ask more questions in the future. I'll try to answer them as well as I can. At this point however I think you need to cover your basics first.

**Comment by TargetFocussed** [comment]
Thank you for taking time. I believe fundamentally I missing some thing simple here....

here is my understanding ....

1. fabio reads updated configuration (list of avaiable service) from consul-server (i.e 
2. Based on running healthy services, it load balance between them.

Very simple.

1. I am asking the question / documentation on where can I find list of services in fabio docker instance 
2. If I run fabio + consul-server on one VM instance and consul-client+registrator+serviceA-1 + serviceB1 +serviceA-2+serviceB-2 on a different VM instance, does it make sens  or works ?

sorry to bother ....I like fabio .....I believe ...I am looking for a documentation that helps in general

thanks

**Comment by killcity** [comment]
You should be able to see the services listed in the Fabio UI (:9998), assuming you have set proper urlprefix tags on the agents advertising your services.

Fabio will connect to the API via local agent. It doesn't have to be running on a node with server running. An agent running in client mode is fine.

**Comment by magiconair** [comment]
First you should see the services in the consul ui and they should all have a green health check other than the SerfCheck. If you run them on different ports you don't need different VMs. Don't use registrator for now. Start from first principles.

This should work on your machine:

```
# terminal 1
consul agent -server -dev -ui-dir <path to ui files>

# terminal 2
fabio

# terminal 3
go get github.com/eBay/fabio
cd $GOPATH/src/github.com/eBay/fabio/demo/server
go build
./server -addr 127.0.0.1:5000 -prefix /foo
# at this point you should see 'server' in the consul ui at localhost:8500
# you should also see one entry in the fabio ui at localhost:9998
# the fabio log should also print
2017/02/18 19:49:48 [INFO] Config updates
+ route add server /foo http://127.0.0.1:5000/ tags "urlprefix-/foo"

# terminal 4
curl localhost:9999/foo
Serving /foo from server on 127.0.0.1:5000

# terminal 5 (2nd instance of server)
./server -prefix /foo -addr 127.0.0.1:5100

# now try the curl command in terminal 4 a couple of times
# you should see responses from both servers
```
