### ISSUE TITLE
Make route update logging format configurable

### ISSUE THREAD

**Issue by magiconair** [eBay/fabio#238]
Large volatile environments can generate large amounts of logs since fabio logs the full routing table on every change. Also, the full routing table isn't as useful as it could be since one would still have to determine the delta to the previous state. 

fabio should get a new config property (e.g. `proxy.log.routefmt=(none|full|diff)`) which defaults to `diff` and logs a unified diff of the routing table changes. `full` would restore the current behavior and `none` would not log any routing table details. 

`none` will still log that the consul state has changed and that fabio had to rebuild the routing table since this is an indicator that the environment and/or the health checks aren't stable and need attention. For the same reason, log-level filtering is not implemented since it would suppress this information.

See #226, #227, #236

**Comment by stevehorsfield** [comment]
Thanks for pushing this forward.

**Comment by avichalbadaya** [comment]
+1 . Thanks Frank !

**Comment by avichalbadaya** [comment]
Looking good. I think this config param/options might be better - `proxy.log.routes=(none|all|delta))`. I don't have a strong opinion for `none` type. As `delta` or `diff` will be filtering out most of the noice, I don't think `none` would add value and as you said, could be misused.

**Comment by magiconair** [comment]
@avichalbadaya Lets drop `none` and see whether someone wants it. I think your config name is better.

**Comment by avichalbadaya** [comment]
👍

**Comment by magiconair** [comment]
`full` -> `all`

**Comment by magiconair** [comment]
Merged to master

**Comment by magiconair** [comment]
@avichalbadaya Would you be willing to share some details about the scale of your project? Would you be interested in being listed in the README as one of the companies using fabio?

**Comment by avichalbadaya** [comment]
Thanks for pushing changes to master. Me and my team is quite appreciative of your support. We would be glad to share more details about our scale/stack, but first we need to get 👍  from our stakeholders. I have already put it forward and should get back to you on this once I get updates from them.

Cheers,
Avichal
