### ISSUE TITLE
feature idea: fabio can be configured to only serve consul services with certain tags

### ISSUE THREAD

**Issue by aerickson** [eBay/fabio#245]
I'd like to use the same Consul cluster to serve internal and external applications. Separate Fabio clusters would only serve services registered with particular tags ('internal' and 'external' in this example).

It sounds like @magiconair handles this by running separate Consul clusters.

**Comment by magiconair** [comment]
@aerickson Check out the `-registry.consul.tagprefix` parameter which should do what you want. Please let me know if you're looking for something else.

https://github.com/eBay/fabio/blob/master/fabio.properties#L467-L475

**Comment by magiconair** [comment]
@aerickson I'm going to close this issue for now since I believe that the solution I've provided answers your question. If it does not then please feel free to comment and I'll re-open if necessary. Thank you.

**Comment by aerickson** [comment]
@magiconair Thanks, that's perfect. :)
