### ISSUE TITLE
Start listener after routing table is initialized

### ISSUE THREAD

**Issue by taharah** [eBay/fabio#248]
I've noticed that when restarting Fabio it clears out the routing tables, which can cause issues temporarily while the routes are re-generated. Would it be possible to be able to persist the current routing table between restarts? Either that or have a startup timer similar to the shutdown one where it will throw a 503 because then the load balancer in front of Fabio that I use (F5) would be able to detect the service as unhealthy still.

**Comment by magiconair** [comment]
I wouldn't persist the table but wait for a first update before starting the listeners. 

Frank Schröder

**Comment by magiconair** [comment]
@taharah I've written a small patch which should do the trick. Can you check whether this works for you?
