### ISSUE TITLE
Is there any option to enable HSTS

### ISSUE THREAD

**Issue by ket4yii** [eBay/fabio#254]
Fabio just doesn't support custom headers. I tried to work it out by ```proxy.header.tls``` and ```proxy.header.tls.value```, and it works, but, you know, it's not convinient. How can I work it out.

**Comment by magiconair** [comment]
No, there isn't at the moment but I can add it. This is a duplicate of #168. Could you please subscribe to that issue? Thx

**Comment by ket4yii** [comment]
Ok, thx
