### ISSUE TITLE
Find the route across the machine, but no response

### ISSUE THREAD

**Issue by badounan** [eBay/fabio#256]
I have two physical machines. IP addresses are 192.168.0.10 and 192.168.0.11 respectively.

Start consul sever and fabio on 192.168.10.

Start the consul client and http server on 192.168.0.11. The json registered to consul's service is as follows:
{"service": {"id": "sampleservice","name":"sampleservice","tags": ["urlprefix-/foo"],"address": "192.168.0.11","port": 8088,"checks": [{"deregisterCriticalServiceAfter": "5m","http": "http://192.168.0.11:8088/foo","interval": "10s"}]}}

Http service is running normally in consul.

But visit http://192.168.0.10:9999/foo, has been no response, there is no log output.

**Comment by magiconair** [comment]
Are both checks in consul green? Is the consul cluster healthy?

Can you provide `curl -i localhost:8500/v1/health/service/sampleservice?pretty` ?

As a side note: use a unique id value for your service, e.g. `<name>-<addr>-<port>` Otherwise, this won't work with multiple instances.

**Comment by badounan** [comment]
I only started the http service on 192.168.0.11.There is only one instance of the service.

If I put fabio, consul and http services are deployed on a machine. no problem.

**Comment by badounan** [comment]
If the address is wrong, the output "No route for ...", which is very correct.

But when i visit a normal address:http://192.168.0.10:9999/foo, without any response, has been waiting.there is no log output.

**Comment by magiconair** [comment]
what does `curl -i http://192.168.0.11:8080/foo` return?

**Comment by badounan** [comment]
yes, when curl -i http://192.168.0.11:8080/foo,the return is normal

**Comment by badounan** [comment]
but when curl -i http://192.168.0.10:9999/foo，noo response, no output, has been waiting for the state

**Comment by magiconair** [comment]
Can you provide `curl -i localhost:8500/v1/health/service/sampleservice?pretty`?

**Comment by badounan** [comment]
[
    {
        "Node": {
            "Node": "n2",
            "Address": "192.168.0.11",
            "TaggedAddresses": null,
            "CreateIndex": 3,
            "ModifyIndex": 20
        },
        "Service": {
            "ID": "sampleservice",
            "Service": "sampleservice",
            "Tags": [
                "urlprefix-/foo"
            ],
            "Address": "192.168.0.11",
            "Port": 8088,
            "EnableTagOverride": false,
            "CreateIndex": 18,
            "ModifyIndex": 20
        },
        "Checks": [
            {
                "Node": "n2",
                "CheckID": "serfHealth",
                "Name": "Serf Health Status",
                "Status": "passing",
                "Notes": "",
                "Output": "Agent alive and reachable",
                "ServiceID": "",
                "ServiceName": "",
                "CreateIndex": 3,
                "ModifyIndex": 3
            },
            {
                "Node": "n2",
                "CheckID": "service:sampleservice",
                "Name": "Service 'sampleservice' check",
                "Status": "passing",
                "Notes": "",
                "Output": "",
                "ServiceID": "sampleservice",
                "ServiceName": "sampleservice",
                "CreateIndex": 18,
                "ModifyIndex": 20
            }
        ]
    }
]

**Comment by magiconair** [comment]
My suspicion is that your consul servers aren't talking to each other. That fabio is talking to consul on 192.168.0.10 and your service is registered on 192.168.0.11.

How did you configure the consul cluster? Can you provide the full and exact commands you ran?

Can you also provide the fabio log? When it starts up it should have a log line like this:

```
route add sampleservice /foo http://192.168.0.11:8088/
```

Can you provide the output of `curl -i http://192.168.0.10/v1/health/service/sampleservice?pretty`.

**Comment by badounan** [comment]
consul agent -server -bootstrap-expect 2 -data-dir /data/test -node n1 -bind=192.168.0.10 -ui-dir ./consul_ui -dc=dc1

consul agent -server -bootstrap-expect 2 -data-dir /data/test -node n1 -bind=192.168.0.11 -dc=dc1

Then on 192.168.0.10,enter: "consul join 192.168.0.11"
Automatic election leader.

**Comment by badounan** [comment]
Yes, Fabio have a log:

`route add sampleservice /foo http://192.168.0.11:8088/`

**Comment by magiconair** [comment]
ok, then fabio has found the service and added a route. Therefore, the consul setup is correct. Can provide the full command and output of these commands assuming fabio listens on port `9999`:

```
curl -i http://192.168.0.10:9999/foo 
curl -i http://192.168.0.11:8088/foo
```

**Comment by magiconair** [comment]
Also, are you sure you've registered the second node with node name `n1`? The health check says `n2`. I suggest copying the commands you typed from the terminal or the shell history.

**Comment by magiconair** [comment]
Sorry, grasping at straws here. I'm sure this is something trivial but I don't see it. If this wouldn't work nothing would work. So bear with me.

**Comment by badounan** [comment]
Hello!
I use Nancy as the http server. When I curl -i http://192.168.0.10:9999/foo, close the http server, fabio have the following error:

http:proxy error:read tcp 192.168.0.10:60188->192.168.0.11:8088: wsarecv:An existing connection was forcibly closed by the remote host.

**Comment by badounan** [comment]
Hello!
I have solved this problem.This is the Http server Nancy problem.

**Comment by badounan** [comment]
Thank you for your answer.

**Comment by magiconair** [comment]
I'm glad you found it. Can you say what the problem was?

Frank Schröder

**Comment by satishviswanathan** [comment]
@badounan If you don't mind can you add the resolution for this issue?
