### ISSUE TITLE
HTTPS upstream added as HTTP

### ISSUE THREAD

**Issue by itatabitovski** [eBay/fabio#259]
Upstream shown as http:// in fabio admin.

```
    "ServiceTags": [
      "ci-fabio-/users",
      "proto=https",
      "tlsskipverify=true",
    ],
```

**Comment by magiconair** [comment]
You mean in the UI?

**Comment by itatabitovski** [comment]
Yes, in the UI I see that the upstream is http://

**Comment by magiconair** [comment]
Yeah, I missed that in the PR. Also the demo server needs some work and I'll update the docs on the wiki.

**Comment by itatabitovski** [comment]
Having the service registered with the tags above does not seem to add it as HTTPS, it is not just a UI issue.

Trying to access a service resulted in:
```
http: proxy error: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

Manually registering the service as described in #260 does not give this error.

**Comment by magiconair** [comment]
These are not individual tags but options for the route. A service can publish more than one route and they can all have different options. 

Try `ci-fabio-/users proto=https tlsskipverify=true` as one tag. That should produce the following route:

```
route add srv /users https://1.2.3.4:5678 opts "tlsskipverify=true proto=https"
```

I'll make sure that this is clear in the documentation.

**Comment by itatabitovski** [comment]
Manually adding the route with one combined tag ```"tlsskipverify=true proto=https"``` works as expected!

How do I register this tag in consul?

**Comment by magiconair** [comment]
You register the tag as one value, e.g.

```
"ServiceTags": [
  "ci-fabio-/users proto=https tlsskipverify=true",
],
```

**Comment by itatabitovski** [comment]
Everything works fine now. Thank you.
