### ISSUE TITLE
How to configure HTTPS upstream manually with tlsskipverify

### ISSUE THREAD

**Issue by itatabitovski** [eBay/fabio#260]
I have tried the following but fabio still complains about invalid certificate.

```
route add svc /test https://IP:28718/ tags "tlsskipverify=true"
```

**Comment by magiconair** [comment]
Try `opts` instead of `tags`

**Comment by magiconair** [comment]
I'll update the docs on the Wiki

**Comment by itatabitovski** [comment]
I am not sure if opts worked. I still get ```proxy error: x509: cannot validate certificate```

However when I ```curl --insecure https://...``` the upstream it works OK.

**Comment by magiconair** [comment]
I'll have a look
