### ISSUE TITLE
difference between cs, proxy.cs

### ISSUE THREAD

**Issue by kostyrev** [eBay/fabio#263]
I'm reading the [docs](https://github.com/eBay/fabio/wiki/Certificate-Stores) and default [fabio.properties](fabio.properties) and I can't grasp concepts behinds cs and proxy.cs.
Which is what?

**Comment by killcity** [comment]
```cs``` is where you declare the cert store name.
```proxy.cs``` is where you point to a specific cert store with respective type and path, if using a path. Here's an example.

proxy.cs = cs=my-certs;type=path;cert=/opt/fabio/ssl;refresh=3s

**Comment by kostyrev** [comment]
I ended up with:
```
proxy.cs = cs=fast;type=file;cert=fast.com.c;key=fast.com.key
proxy.addr=:9999;cs=fast
```
and fabio did start with those in fabio.properties.
but I do not understand the purpose of [this](https://github.com/eBay/fabio/blob/master/fabio.properties#L25) in docs.

**Comment by magiconair** [comment]
@kostyrev No worries. The idea is that you can have a different set of certificates for different listeners. Therefore, the thing that manages the certificates (cert store) is decoupled from the thing that uses them (listener). 

Questions like this are good to understand where the documentation could use some love. So please keep asking.
