### ISSUE TITLE
Refactor listener config

### ISSUE THREAD

**Issue by magiconair** [eBay/fabio#28]
The listener configuration in `proxy.addr` seemed like a good idea but wasn't. To provide parameters for read and write timeout and reuse the same configuration also for the UI (see issue #25) I'm planning to change the configuration of the listeners as follows:

```
# proxy.listen configures one or more listeners for the reverse proxy.
#
# The default is to create a single HTTP listener on :9999 without
# authentication. Listeners which have a valid certificate are on HTTPS. If the
# certificate file contains both the certificate and the private key then the
# 'key' parameter can be omitted. For HTTPS connections X509 client certificate
# authentication can be configured which is set to RequireAndVerifyCert when
# enabled.
#
# All certificates and keys must be in PEM format.
#
# To configure the listener you can set the following options:
#
# proxy.listen.<name>.addr; listen address
# proxy.listen.<name>.tlsCert: path to TLS certificate file
# proxy.listen.<name>.tlsKey: path to TLS key file
# proxy.listen.<name>.clientCert: path to client certficate file
# proxy.listen.<name>.readTimeout: read timeout
# proxy.listen.<name>.writeTimeout: write timeout
```

The same options will be available for the UI/API listener and the same code will start all listeners. 

`proxy.addr` and `ui.addr` will be deprecated with a startup warning and removed in a later release.

**Comment by magiconair** [comment]
Won't happen for 1.0.9 unfortunately.

**Comment by smancke** [comment]
Maybe it would be a good idea to allow a list of certificates for each listener, so that multiple Domains can be served on the same port.

As I saw, golang supports a slice of Certificates in tls.Config{} and should be able to create a mapping of the CommonName and SubjectAlternateName provided in the certificate (see also tls.Config.BuildNameToCertificate())

Maybe the configuration then should be something like:
proxy.listen.<name>.tlsCert.0 =
proxy.listen.<name>.tlsCert.1 =

**Comment by magiconair** [comment]
I've started working on that to support #27 and #70 and #79 - which will support multiple dynamic certificates per listener - and will probably settle for 

`proxy.addr = [host]:port;opt=arg;opt=arg,[host]:port;opt=arg;...`

This allows me to specify an arbitrary number of options without going crazy on parameter parsing. It is a similar approach as with the `GODEBUG` env variable.
