### ISSUE TITLE
Fabio not removing nodes with failed health check

### ISSUE THREAD

**Issue by lensen** [eBay/fabio#34]
Fabio doesn't seem to be removing nodes/routes which have a failed healthcheck. It seems to notice that the health of the service has changed, but keeps trying to send requests to the failed node (resulting in a 'connection refused').
Only when all nodes are failed, the routes are removed. Adding one of the nodes back, puts all nodes back in the routes, resulting in intermitted 'connection refused' responses again.
DNS lookups to consul return the expected result, which are just the passing nodes.

**Comment by magiconair** [comment]
Is this with 1.0.7?

**Comment by lensen** [comment]
So far I've tested 1.0.7, 1.0.6 and 1.0.5.

**Comment by magiconair** [comment]
which consul version are you using?

**Comment by lensen** [comment]
Consul v0.6.0

**Comment by magiconair** [comment]
Ah, haven't tested with consul 0.6.0 yet. Can you post the output of `curl localhost:8500/v1/health/state/any?pretty` and let me know which services should be omitted?

**Comment by magiconair** [comment]
or if you don't want to do that send me a secret gist

**Comment by lensen** [comment]
https://gist.github.com/lensen/0a7814ba07ce6c41718e

The first healthcheck of that node is currently in a critical state, and should be removed. 
Killing the consul agent and causing the serfHealth healthcheck to fail as well doesn't seem to remove the node either.

**Comment by magiconair** [comment]
If I look at this code https://github.com/eBay/fabio/blob/master/registry/consul/passing.go I can't see how it would be included with a status of "critical". Once the service went critical can you check the fabio logs whether the route for this service is actually there. (reminder to dump raw routing table via api...) Could you post the routing table as well, please?

**Comment by lensen** [comment]
I think the problem is that it isn't so much the service is failing (the 002 node is still working, so the service is technically OK), but just one of the nodes is.

Anyway, here is the routing table:
```
#	Service	Host	Path	Dest	Weight
1	local-overview-swap		/overview	http://local-overview-swap-002.localdomain:8080/	50%
2	local-overview-swap		/overview	http://local-overview-swap-001.localdomain:8080/	50%
3	local-content-swap		/content	http://local-content-swap-002.localdomain:8080/	50%
4	local-content-swap		/content	http://local-content-swap-001.localdomain:8080/	50%
```

**Comment by magiconair** [comment]
fabio goes through the health checks for all instances and not per service. If a health check is for a service (ServiceID != "") and has a Status != "passing" then it is omitted. That's why I don't understand how this can happen. However, I've just spotted something in your health checks. Your ServiceID fields are not unique, i.e. you use "local-overview-swap" for both instances. Try making them unique, e.g. "local-overview-swap-node001-8080". I don't think the way you're doing it is correct but I need to check to be sure.

**Comment by lensen** [comment]
Specifying a (unique) ServiceID seems to fix it. Looks like a part of the consul puppet module bit me in ***:
```
define consul::service(
  $ensure         = present,
  $service_name   = $title,
  $id             = $title,
``` 

I dunno if you want to keep this issue open or not, but it might make sense to change some logic here, since the consul DNS interface does seem to assume those nodes are really broken and doesn't return them.

Anyway, thanks for the help.

**Comment by magiconair** [comment]
I'll keep that in mind but for now I'd consider this a config issue and close it. Let me know if there are other issues.
