### ISSUE TITLE
Consul ACL Token

### ISSUE THREAD

**Issue by vpol** [eBay/fabio#36]
I failed to find how can i add consul token to fabio config/command line.

Is it somehow possible?

**Comment by magiconair** [comment]
I was kind of waiting for someone to open that request. I need to add it.

**Comment by magiconair** [comment]
Could you check this version out and see if it works? Best is you build it with `make build` to get a binary with a proper version number. If that works for you then I'll roll it into the next release.

**Comment by vpol** [comment]
Yes, works fine. Thnx.
