### ISSUE TITLE
Expand ${DC} to consul datacenter

### ISSUE THREAD

**Issue by sielaq** [eBay/fabio#55]
Hi,

we need possibility to use variables like  `service_name.service.$DC.$DOMAIN` in tag,
so it will solve issue when having same plans for multiple datacenters and using consul domains.

This can be solved also in other way around. Adding new fabio.property use.consul.domain or tag
 (to use consul domains automatically).
for example:
* input:
service: `consul`
datacenters: `ams`, `fra`
possible consul domains: `consul.service.consul`, `consul.service.ams.consul`, `consul.service.fra.consul`
tag: `use_consul_domain`

* result:
fabio generate 3 routes:
`consul.service.consul`, `consul.service.ams.consul`, `consul.service.fra.consul` that routes to same `consul` service

**Comment by magiconair** [comment]
The use-case as I understand it after some discussion is this:

When services are accessed via fabio through their generic consul DNS name then each service has two names:

```
mysvc.service.consul
mysvc.service.${DC}.consul
```

Services could discover the data center during startup and register the appropriate prefixes. However, this is not possible when registering Docker containers through registrator. By allowing to expand `${DC}` to the data center of the consul agent a service can register two generic prefixes which work in any data center.

```
urlprefix-mysvc.service.consul/
urlprefix-mysvc.service.${DC}.consul/
```

**Comment by magiconair** [comment]
Generating multiple routes for any number of data centers is not necessary.

**Comment by magiconair** [comment]
It is merged.
