### ISSUE TITLE
Latest fabio docker image fails consul check

### ISSUE THREAD

**Issue by aldarund** [eBay/fabio#59]
In previous version all worked fine. Now in atlas fabio at 9998 marked as unhealthy and i see this in logs:

2016/02/20 08:55:06 [WARN] agent: http request failed 'http://<nil>:9998/health': Get http://%3Cnil%3E:9998/health: dial tcp: lookup <nil>: invalid domain name

**Comment by magiconair** [comment]
I think that's fixed with PR #58 which fixes a regression of issue #49. I'll work on a fix for #57 and then release a 1.1.1 which has this change. I think for now either use an older version or specify the ip address.

**Comment by magiconair** [comment]
Should be fixed with the 1.1.1 release.
