### ISSUE TITLE
List among Consul community tools

### ISSUE THREAD

**Issue by sandstrom** [eBay/fabio#6]
Great software :boat: 

This is a good fit for https://consul.io/downloads_tools.html.

**Comment by magiconair** [comment]
Thank you :) Already done. https://github.com/hashicorp/consul/pull/1319

**Comment by sandstrom** [comment]
Ah, nice! Didn't find it on the website, but I probably just missed it.

**Comment by magiconair** [comment]
Nope. It is merged but not live yet.
