### ISSUE TITLE
 Service tag "urlprefix-/foo" will not be discoverable via DNS due to invalid characters.

### ISSUE THREAD

**Issue by pushkaradsule** [eBay/fabio#62]
I am registering service using below command but getting error in consul

 2016/03/02 11:26:17 [INFO] agent: Synced check 'service:fabio-f060b321dadc-9998'
    2016/03/02 11:28:17 [WARN] Service tag "urlprefix-/magic" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2016/03/02 11:28:17 [INFO] agent: Synced service 'nodejs2'
    2016/03/02 11:37:43 [ERR] http: Request /v1/catalog/register, error: Must provide node and address
    2016/03/02 11:41:10 [WARN] Service tag "urlprefix-/magic" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2016/03/02 11:41:11 [INFO] agent: Synced service 'nodejs2'
    2016/03/02 11:41:20 [INFO] agent: Synced service 'nodejs2'
    2016/03/02 11:46:27 [WARN] Service tag "urlprefix-/magic" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2016/03/02 11:46:27 [INFO] agent: Synced service 'nodejs2'
    2016/03/02 14:03:15 [WARN] Service tag "urlprefix-/foo" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2016/03/02 14:03:15 [INFO] agent: Synced service 'sparkjava'
    2016/03/02 14:03:45 [WARN] agent: Check 'service:sparkjava' missed TTL, is now critical
    2016/03/02 14:06:20 [WARN] Service tag "urlprefix-/foo" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2016/03/02 14:06:20 [INFO] agent: Synced service 'sparkjava'
    2016/03/02 14:06:50 [WARN] agent: Check 'service:sparkjava' missed TTL, is now critical

curl -XPUT 172.17.42.1:8500/v1/agent/service/register -d '{
  "ID": "sparkjava",
  "Name": "sparkjava",
  "Tags": [
    "master",
    "urlprefix-/foo"
  ],
  "Address": "127.0.0.1",
  "Port": 8001,
  "Check": {
    "id": "sparkjava",
    "name": "Web App Status",
    "service_id": "web-app",
    "ttl": "30s"
  }
}'

**Comment by magiconair** [comment]
You can ignore that unless you want to use the `urlprefix-/foo` tag in DNS queries.
