### ISSUE TITLE
support middleware(OWIN) to execute some code before recirection

### ISSUE THREAD

**Issue by pushkaradsule** [eBay/fabio#64]
Hi
Not sure if this is a supported and need help if you know some kind of solution, as of now fabio redirect   request to another host:80, but is there any way to execute some code before reaching request to destination host , so it will help to put some kind of common code like authentication in place.

**Comment by magiconair** [comment]
What exactly are you trying to achieve?

**Comment by pushkaradsule** [comment]
I am trying to validate/decrypt  JWT token and passing information in request headers to host ( where api are running)

**Comment by magiconair** [comment]
Why would that be the responsibility of the router? Fabio should know nothing about your application. It just routes requests to your services based on the information they provide.

**Comment by pushkaradsule** [comment]
I got you point, i am just thinking how this will be achieved without having to duplicating code on every service, as we have services in different languages.

**Comment by magiconair** [comment]
How would you do that in HAproxy or nginx? We have the same problem with services in Java and Go. What we have done is to factor out the actual check into a separate service so that the request handler only needs to make a simple call. Then the integration effort is low.

**Comment by pushkaradsule** [comment]
Thanks for prompt reply

**Comment by Cin2ma** [comment]
Unsubscribe

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Fri, Mar 4, 2016 at 2:36 AM -0800, "pushkaradsule" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for prompt reply

-

**Comment by voanhduy1512** [comment]
Hi
In nginx you can do authentication [https://developers.shopware.com/blog/2015/03/02/sso-with-nginx-authrequest-module/](using auth_request module). 
Right now i need to do something like this

```
internet -- HTTP/HTTPS --> Authentication layer -> fabio -- HTTP --> internal services
```
Now i need another balancer in authentication layer because they have multiple instance of authentication services.

I think it would be nice if fabio let me inject some code to run or make http call before process like nginx

**Comment by magiconair** [comment]
@voanhduy1512 In cases where we need this we have an apache in front of fabio. Again, this might be something your app need/can/should handle. The general guideline is that your app should work the same with or without the load balancer.

**Comment by voanhduy1512** [comment]
Thank you for your suggestion.
