### ISSUE TITLE
question: configure through environment variables?

### ISSUE THREAD

**Issue by ketzacoatl** [eBay/fabio#68]
I have been unable to answer this question on my own reading of the docs. Is it possible to pass fabio any of the configuration options as environment variables?

**Comment by smancke** [comment]
Yes, it is. Here is the part from the docs:
https://github.com/eBay/fabio#configuration

**Comment by ketzacoatl** [comment]
> Each property value can also be configured via a corresponding environment variable which has the dots replaced with underscores.

Yes, I am so silly, thanks!
