### ISSUE TITLE
Support statsd

### ISSUE THREAD

**Issue by Sedward** [eBay/fabio#73]
We've been running fabio and we would like the ability to output our metrics to a running statsd server. I don't see it requested anywhere else but I think it would be useful for others eventually.

**Comment by magiconair** [comment]
As long as this is supported by the gometrics library I'm using it should only be a matter of configuration.

**Comment by magiconair** [comment]
Unfortunately, the github.com/rcrowley/go-metrics does not have a statsd reporter but their architecture is pluggable. You can write one...

**Comment by magiconair** [comment]
Jordan Shaw from PubNub sent PR #139 to fix this. Thank you and closing.
