### ISSUE TITLE
register websockets with consul tags

### ISSUE THREAD

**Issue by cookandy** [eBay/fabio#82]
Is it possible to register a websocket rule in fabio using consul tags - i.e. `proto-ws`?  It didn't seem to work for me.

**Comment by magiconair** [comment]
Please have a look here: https://github.com/eBay/fabio#websockets

**Comment by cookandy** [comment]
I'm actually trying to use TCP proxying, but it doesn't look like Fabio support it yet.  I thought maybe websockets would work for TCP connections, but I'm not sure that is true.  In the case of my TCP connections, we won't be able to change the header before the request is sent.  I guess what I really need is TCP proxying.

**Comment by magiconair** [comment]
Yeah. Saw the issue on PanteraS. Not yet. I've got some time scheduled to work on Fabio so maybe I find time to squeeze it in. Pls subscribe to #1

**Comment by cookandy** [comment]
Thanks - I will watch for updates.
