### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by freeman** [eBay/fabio#86]
Fabio looks great ! At work we are mostly a windows team and it would be nice if we could benefit from it :smile: 

Is Windows support available, possible or considered ?

**Comment by magiconair** [comment]
Just try it and let me know how it goes. I don't have an environment to test this in. 

```
go get -u github.com/eBay/fabio
cd $GOPATH/src/github.com/eBay/fabio
git checkout v1.1.1
go build
```

**Comment by freeman** [comment]
Thanks for your answer. I'll try it out and will let you know.

**Comment by magiconair** [comment]
I'm going to close this one for now. Pls re-open if necessary.

**Comment by floekke** [comment]
I'm at the moment experimenting with running fabio on Windows. So far it's working.. Do you see any reasons why that might not be the case now or in the near future?

**Comment by magiconair** [comment]
@floekke No. I'm going to publish Windows binaries from the next release onwards. Please open tickets for issues since I'm not testing this on Windows.

**Comment by floekke** [comment]
Perfect!

**Comment by RXG0** [comment]
We are mostly a windows team and would like to know if there are installation instructions and/or binaries for fabio?

**Comment by magiconair** [comment]
@RXG0 Looks like the switch to goreleaser threw the Windows binary under the bus. https://github.com/fabiolb/fabio/releases/tag/v1.5.4 still has windows binaries. I'll manually add the other ones and fix the release process.

**Comment by magiconair** [comment]
@RXG0 I've added the missing Windows builds for 386 and amd64 to the releases page. 1.5.7 does not build on Windows since I forgot to add a stub function. I'll push a 1.5.7.1 shortly.

https://github.com/fabiolb/fabio/releases
