### ISSUE TITLE
Use Address instead of ServiceAddress?

### ISSUE THREAD

**Issue by chy168** [eBay/fabio#88]
Hello,

I'm trying to integrate fabio with my own service with Consul.
I found Consul might not return "ServiceAddress" when we don't set service.address in Consul definition.

It might cause proxy error, because fabio now depends on "ServiceAddress" as the dest of traffic.

For example:

Consul definition WITH "address" attribute:
```
{"service": {"name": "web", "tags": ["urlprefix-/test1"], "address": "172.17.0.4", "port": 8000, "check": {"script": "curl localhost:8000 >/dev/null 2>&1", "interval": "5s"}}}
```

consul return:
```
$ curl -XGET http://172.17.0.1:8500/v1/catalog/service/web
[
  {
    "Node": "6453bcec8524",
    "Address": "172.17.0.4",
    "ServiceID": "web",
    "ServiceName": "web",
    "ServiceTags": [
      "urlprefix-/test1"
    ],
    "ServiceAddress": "172.17.0.4",
    "ServicePort": 8000,
    "ServiceEnableTagOverride": false,
    "CreateIndex": 22226,
    "ModifyIndex": 22227
  }
]
```

Consul definition WITHOUT "address" attribute:
```
{"service": {"name": "web", "tags": ["urlprefix-/test1"], "port": 8000, "check": {"script": "curl localhost:8000 >/dev/null 2>&1", "interval": "5s"}}}
```

consul return:
```
$ curl -XGET http://172.17.0.1:8500/v1/catalog/service/web
[
  {
    "Node": "6453bcec8524",
    "Address": "172.17.0.4",
    "ServiceID": "web",
    "ServiceName": "web",
    "ServiceTags": [
      "urlprefix-/test1"
    ],
    "ServiceAddress": "",
    "ServicePort": 8000,
    "ServiceEnableTagOverride": false,
    "CreateIndex": 22116,
    "ModifyIndex": 22117
  }
]
```

For non-fixed consul definition file in Docker image, could we just leverage Address instead of ServiceAddress? is that possible?

Please advice! thank you! :)

**Comment by magiconair** [comment]
This vaguely rings a bell but I need to dig through the consul documentation again why that is. For now, I suggest to provide the service address.

**Comment by chy168** [comment]
Thanks for your replay. I also try to find the document describe about this behavior but in vain. I would like to help on this topic, please let me know if any clue we can dig into or do any experiment.

**Comment by magiconair** [comment]
The consul documentation for services https://www.consul.io/docs/agent/services.html says that the service address is optional. 

> The address field can be used to specify a service-specific IP address. By default, the IP address of the agent is used, and this does not need to be provided. 

I've added a change to use the address field if the ServiceAddress is empty. Could you test whether that works for you?

**Comment by mazhack** [comment]
I use ServiceAddress for health check and expose an old IIS web application on windows server 12, consul agent host and windows host are different, so if you change ServiceAddress to Address my prod environment will be break.

So, is good for me that fabio uses Address only if ServiceAddress is empty.

**Comment by magiconair** [comment]
@mazhack `ServiceAddress` takes precedence over `Address`.

**Comment by chy168** [comment]
Hi @magiconair,
Sorry for late reply, I've tested this scenario on my end via the latest release 1.1.2.
Thanks for your time and fabio rocks!!

**Comment by codekoala** [comment]
I could definitely use the option to select ``Address`` over ``ServiceAddress``. I'm trying to use nomad to run some services, and it currently doesn't seem to expose a way to specify ``ServiceAddress`` (because nomad decides where to run each service). I'd be happy to learn that I'm mistaken if that's the case.

Anyway, for my use case, ``Address`` is the server's private IP address and ``ServiceAddress`` is the server's public IP address. In order to save on bandwidth charges and improve response times, I would like to use the ``Address`` value. Also, almost all ports must be locked down against all public traffic (with exceptions for 22, 80, 443, etc).

Here's an example of what I'm seeing:

```json
[
{
  "ID": "11b53a97-489e-1d5f-8af3-91ffc29d903e",
  "Node": "node-01.domain.com",
  "Address": "192.168.0.1",
  "Datacenter": "us-west",
  "TaggedAddresses": {
    "lan": "192.168.0.1",
    "wan": "192.168.0.1"
  },
  "NodeMeta": {},
  "ServiceID": "_nomad-executor-e0a22377-8362-83d8-40e5-ca12c9103150-server-something-urlprefix-something.domain.com/",
  "ServiceName": "nomad-ui",
  "ServiceTags": [
    "prom",
    "urlprefix-something.domain.com/"
  ],
  "ServiceAddress": "172.104.a.b",
  "ServicePort": 3000,
  "ServiceEnableTagOverride": false,
  "CreateIndex": 19297,
  "ModifyIndex": 19297
},
{
  "ID": "b6aece04-f1d0-3811-63d3-2392102b3905",
  "Node": "node-02.domain.com",
  "Address": "192.168.0.2",
  "Datacenter": "us-west",
  "TaggedAddresses": {
    "lan": "192.168.0.2",
    "wan": "192.168.0.2"
  },
  "NodeMeta": {},
  "ServiceID": "_nomad-executor-1ddb350c-7656-e502-50b8-b48f455b645a-server-something-urlprefix-something.domain.com/",
  "ServiceName": "nomad-ui",
  "ServiceTags": [
    "prom",
    "urlprefix-something.domain.com/"
  ],
  "ServiceAddress": "172.104.y.z",
  "ServicePort": 3000,
  "ServiceEnableTagOverride": false,
  "CreateIndex": 19296,
  "ModifyIndex": 19296
}
]
```
