### ISSUE TITLE
Allow tags for fabio service registration

### ISSUE THREAD

**Issue by robholland** [eBay/fabio#96]
Please add a way to configure tags that fabio will set on the service it registers. This will allow us to connect to the admin interface of a specific fabio instance when we have more than one fabio instance in a balancer configuration.

**Comment by magiconair** [comment]
Like this? Could you test it and let me know whether that works for you?

**Comment by robholland** [comment]
Yeah, I'll give that a test, cheers!

**Comment by magiconair** [comment]
Forgot logging.

**Comment by robholland** [comment]
I didn't check the log output, but the tags are set properly :)

**Comment by magiconair** [comment]
ok, then I'll merge that one as well.

**Comment by magiconair** [comment]
merged.
