### ISSUE TITLE
Disable fabio health check in consul

### ISSUE THREAD

**Issue by voanhduy1512** [eBay/fabio#99]
Hi,

When start fabio, it will try to register a health check for itself to consul. In my case, somehow i don't want consul to have a health check for fabio because i run fabio outside of the cluster and it is being monitor by other tool.

Do we have any way to disable it or i will try to send a PR for this.

**Comment by magiconair** [comment]
Not right now but I can add it.

**Comment by voanhduy1512** [comment]
Thank you for your quick respond. I want fabio not registered to consul at all

**Comment by magiconair** [comment]
ok. I'll add it. Not difficult.

**Comment by magiconair** [comment]
That should do the trick. Can you test it, please?
